version: "3.9"
services:
  postgres_db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: "main"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"