version: "3.9"
services:
  postgres_db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: "main"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./src/server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_HOST: "host.docker.internal"
      DB_PORT: "5432"
      DB_USERNAME: "user"
      DB_PASSWORD: "password"
      DB_DATABASE: "main"
    depends_on:
      - postgres_db

  frontend:
    build:
      context: ./src/client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: